"use client";

import { useState } from "react";
import { Download } from "lucide-react";
import {
  FilterPills,
  PageHeader,
  PrimaryButton,
  DataTable,
} from "@/components/dashboard/ui/DashboardUi";

const REPORTS = [
  ["Executive Summary", "Executive", "All Clusters", "May 26, 2026"],
  ["Envoy Gateway Migration Posture", "Security", "prod-eks-apac", "May 25, 2026"],
  ["Cost Optimization Report", "Cost", "All Clusters", "May 25, 2026"],
  ["Cluster Health Report", "Health", "All Clusters", "May 24, 2026"],
  ["Monthly Summary - April", "Executive", "All Clusters", "May 01, 2026"],
];

export function ReportsPage() {
  const [filter, setFilter] = useState("all");

  return (
    <>
      <PageHeader action={<PrimaryButton>Create Report</PrimaryButton>} />
      <div className="space-y-4 p-4 sm:p-6">
        <FilterPills
          active={filter}
          onChange={setFilter}
          items={[
            { id: "all", label: "All Reports" },
            { id: "scheduled", label: "Scheduled" },
            { id: "mine", label: "Generated by Me" },
          ]}
        />
        <div className="rounded-xl border border-kp-border bg-kp-surface/40 p-2 sm:p-4">
          <DataTable
            columns={["Report Name", "Type", "Scope", "Last Generated", "Status", "Actions"]}
            rows={REPORTS.map(([name, type, scope, date]) => [
              <span key={String(name)} className="font-medium text-kp-text">{name}</span>,
              type,
              scope,
              date,
              <span key={`st-${name}`} className="text-kp-green text-xs font-medium">Completed</span>,
              <button key={`dl-${name}`} type="button" className="text-kp-muted hover:text-kp-text">
                <Download className="h-4 w-4" />
              </button>,
            ])}
          />
        </div>
        <p className="text-right text-xs text-kp-muted">Showing 1 to 5 of 20 reports</p>
      </div>
    </>
  );
}
