from __future__ import annotations

import json
from typing import Any

from kubepilot.core.settings import Settings
from kubepilot.intelligence.agents.base import sanitize_commands
from kubepilot.intelligence.client import LLMClient
from kubepilot.intelligence.client.json_parse import parse_llm_json
from kubepilot.intelligence.remediation.templates import fallback_remediation_plan
from kubepilot.intelligence.schemas import ImpactLevel, RemediationPlanResult, RemediationStep

_SYSTEM = """You produce read-only remediation plans for Kubernetes findings.
Reply with a single JSON object only (no markdown, no prose before or after).
Schema:
{"summary":"one short sentence","steps":[{"order":1,"title":"...","description":"...","command":"kubectl ...","command_type":"kubectl|helm|manifest|manual","dry_run_command":null,"verify_command":null}],
"impact_level":"none|low|medium|high","impact_summary":"...","downtime_notes":"...","prerequisites":[],"warnings":[],"rollback_steps":[],"do_not_remediate":false,"do_not_remediate_reason":null}
Include 1-2 steps with short kubectl commands (no quotes inside command strings). Use real namespace and resource names from input.
If accepted_system_requirement, set do_not_remediate true. Never use kubectl delete namespace or --all deletes."""


def _parse_steps(raw_steps: list[Any]) -> list[RemediationStep]:
    steps: list[RemediationStep] = []
    for i, s in enumerate(raw_steps or []):
        if not isinstance(s, dict):
            continue
        steps.append(
            RemediationStep(
                order=int(s.get("order", i + 1)),
                title=str(s.get("title", f"Step {i + 1}")),
                description=str(s.get("description", "")),
                command=s.get("command"),
                command_type=s.get("command_type", "manual"),  # type: ignore[arg-type]
                dry_run_command=s.get("dry_run_command"),
                verify_command=s.get("verify_command"),
            )
        )
    return steps


def _coerce_llm_raw(raw: dict[str, Any]) -> tuple[dict[str, Any], str | None]:
    """Normalize LLM payload; merge JSON accidentally placed in summary."""
    trailing = str(raw.pop("_llm_trailing_note", "") or "").strip() or None
    summary = raw.get("summary")
    if isinstance(summary, str) and summary.strip().startswith("{"):
        inner, extra = parse_llm_json(summary)
        if inner:
            raw = {**inner, **{k: v for k, v in raw.items() if k != "summary"}}
            if extra and not trailing:
                trailing = extra
    return raw, trailing


def _plan_from_llm_raw(raw: dict[str, Any], trailing: str | None) -> RemediationPlanResult:
    steps_raw = sanitize_commands(list(raw.get("steps") or []))
    rollback_raw = sanitize_commands(list(raw.get("rollback_steps") or []))
    impact = str(raw.get("impact_level", "low")).lower()
    if impact not in {e.value for e in ImpactLevel}:
        impact = ImpactLevel.low.value
    note_parts = ["Generated by configured LLM from scan context."]
    if trailing:
        note_parts.append(trailing)
    return RemediationPlanResult(
        summary=str(raw.get("summary", "")),
        steps=_parse_steps(steps_raw),
        impact_level=ImpactLevel(impact),
        impact_summary=str(raw.get("impact_summary", "")),
        downtime_notes=raw.get("downtime_notes"),
        prerequisites=[str(p) for p in raw.get("prerequisites") or []],
        warnings=[str(w) for w in raw.get("warnings") or []],
        rollback_steps=_parse_steps(rollback_raw),
        do_not_remediate=bool(raw.get("do_not_remediate")),
        do_not_remediate_reason=raw.get("do_not_remediate_reason"),
        remediation_source="llm",
        llm_note=" ".join(note_parts),
    )


def run_finding_remediate(
    context_json: str,
    insight: dict[str, Any],
    settings: Settings,
) -> RemediationPlanResult:
    client = LLMClient(settings)
    raw = client.complete_json_sync(_SYSTEM, context_json)
    if raw.get("note"):
        plan = fallback_remediation_plan(insight)
        return plan.model_copy(
            update={
                "remediation_source": "template",
                "llm_note": str(raw.get("note", "")),
            }
        )

    try:
        raw, trailing = _coerce_llm_raw(raw)
        plan = _plan_from_llm_raw(raw, trailing)
        if not plan.steps:
            raise ValueError("LLM returned no steps")
        return plan
    except (TypeError, ValueError, json.JSONDecodeError):
        plan = fallback_remediation_plan(insight)
        return plan.model_copy(
            update={
                "remediation_source": "template",
                "llm_note": "LLM response was invalid or had no steps; used deterministic template.",
            }
        )
