apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepilot-agent
  labels:
    app.kubernetes.io/name: kubepilot-agent
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn | quote }}
